---
title: '[REPORTÉ] "Débuter" avec R en Commençant par le Début ...'
author: Mickaël CANOUIL
date: '2020-03-04'
slug: 2020-03-04-debuter-avec-r
categories:
  - MeetUp
  - R
tags:
  - R
  - RUG
  - MeetUp
---

Bonjour à toutes et tous,
 
R Lille (le groupe des utilisateurs de R) organise son premier MeetUp :  
**"Débuter" avec R en Commençant par le Début ...**

Celui-ci aura lieu le  
REPORTÉ ~~**Vendredi 27 Mars entre 13 h 00 et 14 h 00**~~  
dans  
~~**l’Amphithéâtre A (aile Est) de la Faculté de Médecine de Lille (Pôle Recherche)**~~

Les inscriptions sont par ici : https://www.meetup.com/R-Lille/events/269159363/

> Vous souhaitez démarrer avec de bonnes bases ?  
> Vous suspectez que vous n'avez pas que des bonnes pratiques/habitudes ?  
> Vous aimeriez améliorer ou modifier votre pratique de R, pour être plus efficace et plus autonome ?  
> Vous ignorez ce que sont les fichiers `.Rdata`, `.rds`, `.R`, `.Rmd`, `.Renviron` et/ou `.Rprofile` ?  
> Vous maitrisez les commandes `rm(list = ls())` et `setwd()` ?
>
> Ce premier MeetUp vise à donner quelques trucs et astuces autour de R et de l'IDE Rstudio, ainsi qu'ouvrir la discussion sur quelques "règles/conventions" de bonnes pratiques dans un objectif de reproductibilité.
>
> Lieu : Faculté de Médecine de Lille - Pôle Recherche - Amphithéâtre A (aile Est)

À bientôt !  
Mathilde BOISSEL, Julien HAMONIER et Mickaël CANOUIL
