project:
  type: website

lang: fr
date-format: long
freeze: true

website:
  announcement:
    icon: info-circle
    dismissable: true
    type: success
    position: below-navbar
    content: |
      **Info** - Le groupe reprend ses activités.
      Nous vous tiendrons informé•e•s de la date de notre prochain évènement.
      Une idée, une envie, venez en discuter via [Slack](https://r-grrr.slack.com/archives/C042K6XB34G) ou [courriel](mailto:contact@rlille.fr).
  title: "R Lille - Groupe des Utilisateurs•rices R de Lille"
  description: "Groupe des Utilisateurs•rices de R de Lille"
  favicon: /media/icon.svg
  image: /media/social.png
  site-url: https://rlille.fr
  repo-url: https://github.com/RLille/rlille.fr/
  repo-actions: [edit, issue]
  open-graph:
    title: "R Lille"
    description: "Groupe des Utilisateurs•rices de R de Lille"
    image: /media/social.png
  twitter-card:
    title: "R Lille"
    description: "Groupe des Utilisateurs•rices de R de Lille"
    image: /media/social.png
    site: "@RLilleRUG"
    creator: "@MickaelCanouil"
    card-style: summary_large_image
  page-navigation: true
  page-footer:
    left: |
      Powered by [Quarto](https://quarto.org).
    center: |
      &copy; 2024 R Lille (R User Group).  
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
    right: |
      Supported by [<img src="/media/RConsortium_Horizontal_Pantone.png" alt="R Consortium Logo" style="height:1.5em;"/>](https://www.r-consortium.org/).
    border: true
  navbar:
    search: true
    logo: media/icon.svg
    right:
      - text: À Propos
        href: about.qmd
      - text: "{{< fa brands meetup >}}"
        href: https://www.meetup.com/R-Lille/
      - text: "{{< fa brands github >}}"
        href: https://github.com/RLille/
      - text: "{{< fa brands twitter >}}"
        href: https://twitter.com/RLille_RUG
      - text: "{{< fa brands youtube >}}"
        href: https://www.youtube.com/c/RLille
      - text: "{{< fa brands slack >}}"
        href: https://r-grrr.slack.com/archives/C042K6XB34G

format:
  html:
    theme: simplex
    email-obfuscation: javascript
