project:
  type: website
website:
  title: "R Lille - Groupe des Utilisateurs•rices R de Lille"
  description: "Groupe des Utilisateurs•rices de R de Lille"
  favicon: /media/icon.svg
  image: /media/social.png
  site-url: https://rlille.fr
  repo-url: https://github.com/RLille/rlille.fr/
  repo-actions: [edit, issue]
  open-graph:
    title: "R Lille"
    description: "Groupe des Utilisateurs•rices de R de Lille"
    image: /media/social.png
  twitter-card:
    title: "R Lille"
    description: "Groupe des Utilisateurs•rices de R de Lille"
    image: /media/social.png
    site: "@RLilleRUG"
    creator: "@MickaelCanouil"
    card-style: summary_large_image
  comments: 
    utterances:
      repo: mcanouil/rlille.fr
  page-navigation: true
  page-footer:
    left: |
      Powered by [Quarto](https://quarto.org).
    center: |
      &copy; 2022 R Lille (R User Group).  
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
    right: |
      Supported by [<img src="/media/RConsortium_Horizontal_Pantone.png" alt="R Consortium Logo" style="height:1.5em;"/>](https://www.r-consortium.org/).
    border: true
  navbar:
    search: true
    logo: media/icon.svg
    right:
      - text: À Propos
        href: about.qmd
      - text: "{{< fa meetup >}}"
        href: https://www.meetup.com/R-Lille/
      - icon: github
        href: https://github.com/RLille/
      - icon: twitter
        href: https://twitter.com/RLille_RUG
      - icon: youtube
        href: https://www.youtube.com/channel/UCCRIHidGlMgADMkGrl8eKiQ
      - icon: slack
        href: https://rlille.slack.com/
format:
  html:
    theme: simplex
    css: styles.css
    lang: fr
    date-format: long
