baseURL = "https://rlille.netlify.app/"
languageCode = "fr-FR"
title = "R Lille"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "(^|/)renv$", "renv\\.lock$"]
publishDir = "www"

[params]
    author = "R Lille"
    description = "Groupe des Utilisateurs de R de Lille."
    githubUsername = "RLille"
    accent = "#d40000"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["r", "go", "haskell", "kotlin", "scala", "swift"]
    dateFormat = "02-01-2006" # "2006-01-02"
    logo = "/media/icon.png"
    logoSupport = "/media/RConsortium_Horizontal_Pantone.png"
    copyright = "&copy; 2020-2021 R Lille.<br> Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal) (modified by [Mickaël Canouil](https://mickael.canouil.fr))."

[[menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "À Propos"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/RLille"
    name = "fab fa-github"
    weight = 1

[[menu.icon]]
    url = "http://meetup.rlille.fr"
    name = "fab fa-meetup"
    weight = 2
    
[[menu.icon]]
    url = "http://youtube.rlille.fr"
    name = "fab fa-youtube"
    weight = 3
    
[[menu.icon]]
    url = "https://twitter.com/RLille_RUG"
    name = "fab fa-twitter"
    weight = 4
    
[[menu.icon]]
    url = "https://rlille.slack.com"
    name = "fab fa-slack"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
